### ISSUE TITLE
Adding MuesliSwaps Concentrated liquidity pools

### ISSUE THREAD

**Issue by nielstron** [Cardano-Fans/crfa-offchain-data-registry#143]
@MuesliSwapTeam has recently launched concentrated liquidity pools. As I understand it, they interact with the normal orderbook.

This is the contract address: `addr1z9qndmhduxjfqvz9rm36p8vsp9vm4l40mx6ndevngkk8srm28uczn6ce6zd5nx2dgr2sza96juq73qz4uhsdxaq74ghs3mz5fw`. Please consider adding it to the list

**Comment by clawoo** [comment]
done
