### ISSUE TITLE
[FR] Interested on easily serving this data as a REST API?

### ISSUE THREAD

**Issue by rcmorano** [Cardano-Fans/crfa-offchain-data-registry#49]
Hey, first of all, thanks for building this! Until we find a better way to maintain these registries on-chain, I find these data collections in JSON format very useful.

I've just added a wrapper for the official [cardano-token-registry](https://github.com/cardano-foundation/cardano-token-registry#server) to serve its data as a mocked API and was wondering if serving this repo in the same way is something you'd be interested on.

I could adapt my work for the [dbless-cardano-token-registry](https://gitlab.com/gimbalabs/dandelion/dbless-cardano-token-registry) and send a PR to this repo if it helps. I will probably do it anyways and integrate it as a Dandelion service, but just wanted to know if contributing the code in this repo works for you. Let me know WDYT :)

**Comment by matiwinnetou** [comment]
We already have this but it is not open source. I can add you as a contributor. It is a simple java service.

**Comment by ggaabe** [comment]
Is there any chance that this might be open sourced soon?
